// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqcQEfEXhRUn2Bn4900aOP7BZfxphsKss',
    appId: '1:778042737982:web:9f3a3436de44f1f1c9586f',
    messagingSenderId: '778042737982',
    projectId: 'jocit-b0c8a',
    authDomain: 'jocit-b0c8a.firebaseapp.com',
    storageBucket: 'jocit-b0c8a.appspot.com',
    measurementId: 'G-PC7LLJ29LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO4zXqWIEVjbMfksvWzDNHPq_bGlgcw-k',
    appId: '1:778042737982:android:5588adb07c0ea049c9586f',
    messagingSenderId: '778042737982',
    projectId: 'jocit-b0c8a',
    storageBucket: 'jocit-b0c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PEXhJ8e-L7yQxD7cWjL6LQkED0BCvI8',
    appId: '1:778042737982:ios:dd455251735d2271c9586f',
    messagingSenderId: '778042737982',
    projectId: 'jocit-b0c8a',
    storageBucket: 'jocit-b0c8a.appspot.com',
    iosClientId: '778042737982-b01ffll0frt00lk8jri52t4bqagpmmnf.apps.googleusercontent.com',
    iosBundleId: 'com.jocit.jocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PEXhJ8e-L7yQxD7cWjL6LQkED0BCvI8',
    appId: '1:778042737982:ios:dd455251735d2271c9586f',
    messagingSenderId: '778042737982',
    projectId: 'jocit-b0c8a',
    storageBucket: 'jocit-b0c8a.appspot.com',
    iosClientId: '778042737982-b01ffll0frt00lk8jri52t4bqagpmmnf.apps.googleusercontent.com',
    iosBundleId: 'com.jocit.jocs',
  );
}
